package: rexql
version: '1.0.0-beta'
license: MIT
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/rexql/issues'

page:
  title: 'translate:rexql_title'
  icon: rex-icon fa-exchange-alt
  subpages:
    overview:
      title: 'Übersicht'
      icon: fa fa-home
      perm: uploader[bulk_rework]
    playground:
      title: 'Playground'
      icon: fa fa-play
      perm: rexql[playground]
    permissions:
      title: 'translate:rexql_permissions'
      icon: rex-icon rex-icon-user
      perm: rexql[permissions]
    config:
      title: 'translate:rexql_config'
      icon: rex-icon fa-cog
      perm: rexql[config]
    webhooks:
      title: 'Webhooks'
      icon: fa fa-bell
      perm: rexql[webhooks]
    docs:
      title: 'translate:rexql_docs'
      itemClass: 'pull-right'
      icon: rex-icon fa-info-circle

requires:
  redaxo: '^5.17.0'
  php:
    version: '^8.1'

installer_ignore:
  - .tools
  - node_modules
  - assets-src
